backend:
  name: git-gateway
  branch: main

identity_url: https://dancing-crumble-e35ce5.netlify.app/.netlify/identity
gateway_url: https://dancing-crumble-e35ce5.netlify.app/.netlify/git

site_url: https://tnfswov.in
display_url: https://tnfswov.in

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      
